//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaAlfabeto
    {
        public Nullable<int> fiIdKey { get; set; }
        public string fcValue { get; set; }
    }
}
